exports.dex = {
	"bulbasaur": ["Grass", "Poison"],
	"ivysaur": ["Grass", "Poison"],
	"venusaur": ["Grass", "Poison"],
	"venusaurmega": ["Grass", "Poison"],
	"charmander": ["Fire"],
	"charmeleon": ["Fire"],
	"charizard": ["Fire", "Flying"],
	"charizardmegax": ["Fire", "Dragon"],
	"charizardmegay": ["Fire", "Flying"],
	"squirtle": ["Water"],
	"wartortle": ["Water"],
	"blastoise": ["Water"],
	"blastoisemega": ["Water"],
	"caterpie": ["Bug"],
	"metapod": ["Bug"],
	"butterfree": ["Bug", "Flying"],
	"weedle": ["Bug", "Poison"],
	"kakuna": ["Bug", "Poison"],
	"beedrill": ["Bug", "Poison"],
	"beedrillmega": ["Bug", "Poison"],
	"pidgey": ["Normal", "Flying"],
	"pidgeotto": ["Normal", "Flying"],
	"pidgeot": ["Normal", "Flying"],
	"pidgeotmega": ["Normal", "Flying"],
	"rattata": ["Normal"],
	"rattataalola": ["Dark", "Normal"],
	"raticate": ["Normal"],
	"raticatealola": ["Dark", "Normal"],
	"spearow": ["Normal", "Flying"],
	"fearow": ["Normal", "Flying"],
	"ekans": ["Poison"],
	"arbok": ["Poison"],
	"pikachu": ["Electric"],
	"pikachucosplay": ["Electric"],
	"pikachurockstar": ["Electric"],
	"pikachubelle": ["Electric"],
	"pikachupopstar": ["Electric"],
	"pikachuphd": ["Electric"],
	"pikachulibre": ["Electric"],
	"pikachuoriginal": ["Electric"],
	"pikachuhoenn": ["Electric"],
	"pikachusinnoh": ["Electric"],
	"pikachuunova": ["Electric"],
	"pikachukalos": ["Electric"],
	"pikachualola": ["Electric"],
	"pikachupartner": ["Electric"],
	"raichu": ["Electric"],
	"raichualola": ["Electric", "Psychic"],
	"sandshrew": ["Ground"],
	"sandshrewalola": ["Ice", "Steel"],
	"sandslash": ["Ground"],
	"sandslashalola": ["Ice", "Steel"],
	"nidoranf": ["Poison"],
	"nidorina": ["Poison"],
	"nidoqueen": ["Poison", "Ground"],
	"nidoranm": ["Poison"],
	"nidorino": ["Poison"],
	"nidoking": ["Poison", "Ground"],
	"clefairy": ["Fairy"],
	"clefable": ["Fairy"],
	"vulpix": ["Fire"],
	"vulpixalola": ["Ice"],
	"ninetales": ["Fire"],
	"ninetalesalola": ["Ice", "Fairy"],
	"jigglypuff": ["Normal", "Fairy"],
	"wigglytuff": ["Normal", "Fairy"],
	"zubat": ["Poison", "Flying"],
	"golbat": ["Poison", "Flying"],
	"oddish": ["Grass", "Poison"],
	"gloom": ["Grass", "Poison"],
	"vileplume": ["Grass", "Poison"],
	"paras": ["Bug", "Grass"],
	"parasect": ["Bug", "Grass"],
	"venonat": ["Bug", "Poison"],
	"venomoth": ["Bug", "Poison"],
	"diglett": ["Ground"],
	"diglettalola": ["Ground", "Steel"],
	"dugtrio": ["Ground"],
	"dugtrioalola": ["Ground", "Steel"],
	"meowth": ["Normal"],
	"meowthalola": ["Dark"],
	"persian": ["Normal"],
	"persianalola": ["Dark"],
	"psyduck": ["Water"],
	"golduck": ["Water"],
	"mankey": ["Fighting"],
	"primeape": ["Fighting"],
	"growlithe": ["Fire"],
	"arcanine": ["Fire"],
	"poliwag": ["Water"],
	"poliwhirl": ["Water"],
	"poliwrath": ["Water", "Fighting"],
	"abra": ["Psychic"],
	"kadabra": ["Psychic"],
	"alakazam": ["Psychic"],
	"alakazammega": ["Psychic"],
	"machop": ["Fighting"],
	"machoke": ["Fighting"],
	"machamp": ["Fighting"],
	"bellsprout": ["Grass", "Poison"],
	"weepinbell": ["Grass", "Poison"],
	"victreebel": ["Grass", "Poison"],
	"tentacool": ["Water", "Poison"],
	"tentacruel": ["Water", "Poison"],
	"geodude": ["Rock", "Ground"],
	"geodudealola": ["Rock", "Electric"],
	"graveler": ["Rock", "Ground"],
	"graveleralola": ["Rock", "Electric"],
	"golem": ["Rock", "Ground"],
	"golemalola": ["Rock", "Electric"],
	"ponyta": ["Fire"],
	"rapidash": ["Fire"],
	"slowpoke": ["Water", "Psychic"],
	"slowbro": ["Water", "Psychic"],
	"slowbromega": ["Water", "Psychic"],
	"magnemite": ["Electric", "Steel"],
	"magneton": ["Electric", "Steel"],
	"farfetchd": ["Normal", "Flying"],
	"doduo": ["Normal", "Flying"],
	"dodrio": ["Normal", "Flying"],
	"seel": ["Water"],
	"dewgong": ["Water", "Ice"],
	"grimer": ["Poison"],
	"grimeralola": ["Poison", "Dark"],
	"muk": ["Poison"],
	"mukalola": ["Poison", "Dark"],
	"shellder": ["Water"],
	"cloyster": ["Water", "Ice"],
	"gastly": ["Ghost", "Poison"],
	"haunter": ["Ghost", "Poison"],
	"gengar": ["Ghost", "Poison"],
	"gengarmega": ["Ghost", "Poison"],
	"onix": ["Rock", "Ground"],
	"drowzee": ["Psychic"],
	"hypno": ["Psychic"],
	"krabby": ["Water"],
	"kingler": ["Water"],
	"voltorb": ["Electric"],
	"electrode": ["Electric"],
	"exeggcute": ["Grass", "Psychic"],
	"exeggutor": ["Grass", "Psychic"],
	"exeggutoralola": ["Grass", "Dragon"],
	"cubone": ["Ground"],
	"marowak": ["Ground"],
	"marowakalola": ["Fire", "Ghost"],
	"hitmonlee": ["Fighting"],
	"hitmonchan": ["Fighting"],
	"lickitung": ["Normal"],
	"koffing": ["Poison"],
	"weezing": ["Poison"],
	"rhyhorn": ["Ground", "Rock"],
	"rhydon": ["Ground", "Rock"],
	"chansey": ["Normal"],
	"tangela": ["Grass"],
	"kangaskhan": ["Normal"],
	"kangaskhanmega": ["Normal"],
	"horsea": ["Water"],
	"seadra": ["Water"],
	"goldeen": ["Water"],
	"seaking": ["Water"],
	"staryu": ["Water"],
	"starmie": ["Water", "Psychic"],
	"mrmime": ["Psychic", "Fairy"],
	"scyther": ["Bug", "Flying"],
	"jynx": ["Ice", "Psychic"],
	"electabuzz": ["Electric"],
	"magmar": ["Fire"],
	"pinsir": ["Bug"],
	"pinsirmega": ["Bug", "Flying"],
	"tauros": ["Normal"],
	"magikarp": ["Water"],
	"gyarados": ["Water", "Flying"],
	"gyaradosmega": ["Water", "Dark"],
	"lapras": ["Water", "Ice"],
	"ditto": ["Normal"],
	"eevee": ["Normal"],
	"vaporeon": ["Water"],
	"jolteon": ["Electric"],
	"flareon": ["Fire"],
	"porygon": ["Normal"],
	"omanyte": ["Rock", "Water"],
	"omastar": ["Rock", "Water"],
	"kabuto": ["Rock", "Water"],
	"kabutops": ["Rock", "Water"],
	"aerodactyl": ["Rock", "Flying"],
	"aerodactylmega": ["Rock", "Flying"],
	"snorlax": ["Normal"],
	"articuno": ["Ice", "Flying"],
	"zapdos": ["Electric", "Flying"],
	"moltres": ["Fire", "Flying"],
	"dratini": ["Dragon"],
	"dragonair": ["Dragon"],
	"dragonite": ["Dragon", "Flying"],
	"mewtwo": ["Psychic"],
	"mewtwomegax": ["Psychic", "Fighting"],
	"mewtwomegay": ["Psychic"],
	"mew": ["Psychic"],
	"chikorita": ["Grass"],
	"bayleef": ["Grass"],
	"meganium": ["Grass"],
	"cyndaquil": ["Fire"],
	"quilava": ["Fire"],
	"typhlosion": ["Fire"],
	"totodile": ["Water"],
	"croconaw": ["Water"],
	"feraligatr": ["Water"],
	"sentret": ["Normal"],
	"furret": ["Normal"],
	"hoothoot": ["Normal", "Flying"],
	"noctowl": ["Normal", "Flying"],
	"ledyba": ["Bug", "Flying"],
	"ledian": ["Bug", "Flying"],
	"spinarak": ["Bug", "Poison"],
	"ariados": ["Bug", "Poison"],
	"crobat": ["Poison", "Flying"],
	"chinchou": ["Water", "Electric"],
	"lanturn": ["Water", "Electric"],
	"pichu": ["Electric"],
	"pichuspikyeared": ["Electric"],
	"cleffa": ["Fairy"],
	"igglybuff": ["Normal", "Fairy"],
	"togepi": ["Fairy"],
	"togetic": ["Fairy", "Flying"],
	"natu": ["Psychic", "Flying"],
	"xatu": ["Psychic", "Flying"],
	"mareep": ["Electric"],
	"flaaffy": ["Electric"],
	"ampharos": ["Electric"],
	"ampharosmega": ["Electric", "Dragon"],
	"bellossom": ["Grass"],
	"marill": ["Water", "Fairy"],
	"azumarill": ["Water", "Fairy"],
	"sudowoodo": ["Rock"],
	"politoed": ["Water"],
	"hoppip": ["Grass", "Flying"],
	"skiploom": ["Grass", "Flying"],
	"jumpluff": ["Grass", "Flying"],
	"aipom": ["Normal"],
	"sunkern": ["Grass"],
	"sunflora": ["Grass"],
	"yanma": ["Bug", "Flying"],
	"wooper": ["Water", "Ground"],
	"quagsire": ["Water", "Ground"],
	"espeon": ["Psychic"],
	"umbreon": ["Dark"],
	"murkrow": ["Dark", "Flying"],
	"slowking": ["Water", "Psychic"],
	"misdreavus": ["Ghost"],
	"unown": ["Psychic"],
	"wobbuffet": ["Psychic"],
	"girafarig": ["Normal", "Psychic"],
	"pineco": ["Bug"],
	"forretress": ["Bug", "Steel"],
	"dunsparce": ["Normal"],
	"gligar": ["Ground", "Flying"],
	"steelix": ["Steel", "Ground"],
	"steelixmega": ["Steel", "Ground"],
	"snubbull": ["Fairy"],
	"granbull": ["Fairy"],
	"qwilfish": ["Water", "Poison"],
	"scizor": ["Bug", "Steel"],
	"scizormega": ["Bug", "Steel"],
	"shuckle": ["Bug", "Rock"],
	"heracross": ["Bug", "Fighting"],
	"heracrossmega": ["Bug", "Fighting"],
	"sneasel": ["Dark", "Ice"],
	"teddiursa": ["Normal"],
	"ursaring": ["Normal"],
	"slugma": ["Fire"],
	"magcargo": ["Fire", "Rock"],
	"swinub": ["Ice", "Ground"],
	"piloswine": ["Ice", "Ground"],
	"corsola": ["Water", "Rock"],
	"remoraid": ["Water"],
	"octillery": ["Water"],
	"delibird": ["Ice", "Flying"],
	"mantine": ["Water", "Flying"],
	"skarmory": ["Steel", "Flying"],
	"houndour": ["Dark", "Fire"],
	"houndoom": ["Dark", "Fire"],
	"houndoommega": ["Dark", "Fire"],
	"kingdra": ["Water", "Dragon"],
	"phanpy": ["Ground"],
	"donphan": ["Ground"],
	"porygon2": ["Normal"],
	"stantler": ["Normal"],
	"smeargle": ["Normal"],
	"pokestarsmeargle": ["Normal"],
	"tyrogue": ["Fighting"],
	"hitmontop": ["Fighting"],
	"smoochum": ["Ice", "Psychic"],
	"elekid": ["Electric"],
	"magby": ["Fire"],
	"miltank": ["Normal"],
	"blissey": ["Normal"],
	"raikou": ["Electric"],
	"entei": ["Fire"],
	"suicune": ["Water"],
	"larvitar": ["Rock", "Ground"],
	"pupitar": ["Rock", "Ground"],
	"tyranitar": ["Rock", "Dark"],
	"tyranitarmega": ["Rock", "Dark"],
	"lugia": ["Psychic", "Flying"],
	"hooh": ["Fire", "Flying"],
	"celebi": ["Psychic", "Grass"],
	"treecko": ["Grass"],
	"grovyle": ["Grass"],
	"sceptile": ["Grass"],
	"sceptilemega": ["Grass", "Dragon"],
	"torchic": ["Fire"],
	"combusken": ["Fire", "Fighting"],
	"blaziken": ["Fire", "Fighting"],
	"blazikenmega": ["Fire", "Fighting"],
	"mudkip": ["Water"],
	"marshtomp": ["Water", "Ground"],
	"swampert": ["Water", "Ground"],
	"swampertmega": ["Water", "Ground"],
	"poochyena": ["Dark"],
	"mightyena": ["Dark"],
	"zigzagoon": ["Normal"],
	"linoone": ["Normal"],
	"wurmple": ["Bug"],
	"silcoon": ["Bug"],
	"beautifly": ["Bug", "Flying"],
	"cascoon": ["Bug"],
	"dustox": ["Bug", "Poison"],
	"lotad": ["Water", "Grass"],
	"lombre": ["Water", "Grass"],
	"ludicolo": ["Water", "Grass"],
	"seedot": ["Grass"],
	"nuzleaf": ["Grass", "Dark"],
	"shiftry": ["Grass", "Dark"],
	"taillow": ["Normal", "Flying"],
	"swellow": ["Normal", "Flying"],
	"wingull": ["Water", "Flying"],
	"pelipper": ["Water", "Flying"],
	"ralts": ["Psychic", "Fairy"],
	"kirlia": ["Psychic", "Fairy"],
	"gardevoir": ["Psychic", "Fairy"],
	"gardevoirmega": ["Psychic", "Fairy"],
	"surskit": ["Bug", "Water"],
	"masquerain": ["Bug", "Flying"],
	"shroomish": ["Grass"],
	"breloom": ["Grass", "Fighting"],
	"slakoth": ["Normal"],
	"vigoroth": ["Normal"],
	"slaking": ["Normal"],
	"nincada": ["Bug", "Ground"],
	"ninjask": ["Bug", "Flying"],
	"shedinja": ["Bug", "Ghost"],
	"whismur": ["Normal"],
	"loudred": ["Normal"],
	"exploud": ["Normal"],
	"makuhita": ["Fighting"],
	"hariyama": ["Fighting"],
	"azurill": ["Normal", "Fairy"],
	"nosepass": ["Rock"],
	"skitty": ["Normal"],
	"delcatty": ["Normal"],
	"sableye": ["Dark", "Ghost"],
	"sableyemega": ["Dark", "Ghost"],
	"mawile": ["Steel", "Fairy"],
	"mawilemega": ["Steel", "Fairy"],
	"aron": ["Steel", "Rock"],
	"lairon": ["Steel", "Rock"],
	"aggron": ["Steel", "Rock"],
	"aggronmega": ["Steel"],
	"meditite": ["Fighting", "Psychic"],
	"medicham": ["Fighting", "Psychic"],
	"medichammega": ["Fighting", "Psychic"],
	"electrike": ["Electric"],
	"manectric": ["Electric"],
	"manectricmega": ["Electric"],
	"plusle": ["Electric"],
	"minun": ["Electric"],
	"volbeat": ["Bug"],
	"illumise": ["Bug"],
	"roselia": ["Grass", "Poison"],
	"gulpin": ["Poison"],
	"swalot": ["Poison"],
	"carvanha": ["Water", "Dark"],
	"sharpedo": ["Water", "Dark"],
	"sharpedomega": ["Water", "Dark"],
	"wailmer": ["Water"],
	"wailord": ["Water"],
	"numel": ["Fire", "Ground"],
	"camerupt": ["Fire", "Ground"],
	"cameruptmega": ["Fire", "Ground"],
	"torkoal": ["Fire"],
	"spoink": ["Psychic"],
	"grumpig": ["Psychic"],
	"spinda": ["Normal"],
	"trapinch": ["Ground"],
	"vibrava": ["Ground", "Dragon"],
	"flygon": ["Ground", "Dragon"],
	"cacnea": ["Grass"],
	"cacturne": ["Grass", "Dark"],
	"swablu": ["Normal", "Flying"],
	"altaria": ["Dragon", "Flying"],
	"altariamega": ["Dragon", "Fairy"],
	"zangoose": ["Normal"],
	"seviper": ["Poison"],
	"lunatone": ["Rock", "Psychic"],
	"solrock": ["Rock", "Psychic"],
	"barboach": ["Water", "Ground"],
	"whiscash": ["Water", "Ground"],
	"corphish": ["Water"],
	"crawdaunt": ["Water", "Dark"],
	"baltoy": ["Ground", "Psychic"],
	"claydol": ["Ground", "Psychic"],
	"lileep": ["Rock", "Grass"],
	"cradily": ["Rock", "Grass"],
	"anorith": ["Rock", "Bug"],
	"armaldo": ["Rock", "Bug"],
	"feebas": ["Water"],
	"milotic": ["Water"],
	"castform": ["Normal"],
	"castformsunny": ["Fire"],
	"castformrainy": ["Water"],
	"castformsnowy": ["Ice"],
	"kecleon": ["Normal"],
	"shuppet": ["Ghost"],
	"banette": ["Ghost"],
	"banettemega": ["Ghost"],
	"duskull": ["Ghost"],
	"dusclops": ["Ghost"],
	"tropius": ["Grass", "Flying"],
	"chimecho": ["Psychic"],
	"absol": ["Dark"],
	"absolmega": ["Dark"],
	"wynaut": ["Psychic"],
	"snorunt": ["Ice"],
	"glalie": ["Ice"],
	"glaliemega": ["Ice"],
	"spheal": ["Ice", "Water"],
	"sealeo": ["Ice", "Water"],
	"walrein": ["Ice", "Water"],
	"clamperl": ["Water"],
	"huntail": ["Water"],
	"gorebyss": ["Water"],
	"relicanth": ["Water", "Rock"],
	"luvdisc": ["Water"],
	"bagon": ["Dragon"],
	"shelgon": ["Dragon"],
	"salamence": ["Dragon", "Flying"],
	"salamencemega": ["Dragon", "Flying"],
	"beldum": ["Steel", "Psychic"],
	"metang": ["Steel", "Psychic"],
	"metagross": ["Steel", "Psychic"],
	"metagrossmega": ["Steel", "Psychic"],
	"regirock": ["Rock"],
	"regice": ["Ice"],
	"registeel": ["Steel"],
	"latias": ["Dragon", "Psychic"],
	"latiasmega": ["Dragon", "Psychic"],
	"latios": ["Dragon", "Psychic"],
	"latiosmega": ["Dragon", "Psychic"],
	"kyogre": ["Water"],
	"kyogreprimal": ["Water"],
	"groudon": ["Ground"],
	"groudonprimal": ["Ground", "Fire"],
	"rayquaza": ["Dragon", "Flying"],
	"rayquazamega": ["Dragon", "Flying"],
	"jirachi": ["Steel", "Psychic"],
	"deoxys": ["Psychic"],
	"deoxysattack": ["Psychic"],
	"deoxysdefense": ["Psychic"],
	"deoxysspeed": ["Psychic"],
	"turtwig": ["Grass"],
	"grotle": ["Grass"],
	"torterra": ["Grass", "Ground"],
	"chimchar": ["Fire"],
	"monferno": ["Fire", "Fighting"],
	"infernape": ["Fire", "Fighting"],
	"piplup": ["Water"],
	"prinplup": ["Water"],
	"empoleon": ["Water", "Steel"],
	"starly": ["Normal", "Flying"],
	"staravia": ["Normal", "Flying"],
	"staraptor": ["Normal", "Flying"],
	"bidoof": ["Normal"],
	"bibarel": ["Normal", "Water"],
	"kricketot": ["Bug"],
	"kricketune": ["Bug"],
	"shinx": ["Electric"],
	"luxio": ["Electric"],
	"luxray": ["Electric"],
	"budew": ["Grass", "Poison"],
	"roserade": ["Grass", "Poison"],
	"cranidos": ["Rock"],
	"rampardos": ["Rock"],
	"shieldon": ["Rock", "Steel"],
	"bastiodon": ["Rock", "Steel"],
	"burmy": ["Bug"],
	"wormadam": ["Bug", "Grass"],
	"wormadamsandy": ["Bug", "Ground"],
	"wormadamtrash": ["Bug", "Steel"],
	"mothim": ["Bug", "Flying"],
	"combee": ["Bug", "Flying"],
	"vespiquen": ["Bug", "Flying"],
	"pachirisu": ["Electric"],
	"buizel": ["Water"],
	"floatzel": ["Water"],
	"cherubi": ["Grass"],
	"cherrim": ["Grass"],
	"cherrimsunshine": ["Grass"],
	"shellos": ["Water"],
	"gastrodon": ["Water", "Ground"],
	"ambipom": ["Normal"],
	"drifloon": ["Ghost", "Flying"],
	"drifblim": ["Ghost", "Flying"],
	"buneary": ["Normal"],
	"lopunny": ["Normal"],
	"lopunnymega": ["Normal", "Fighting"],
	"mismagius": ["Ghost"],
	"honchkrow": ["Dark", "Flying"],
	"glameow": ["Normal"],
	"purugly": ["Normal"],
	"chingling": ["Psychic"],
	"stunky": ["Poison", "Dark"],
	"skuntank": ["Poison", "Dark"],
	"bronzor": ["Steel", "Psychic"],
	"bronzong": ["Steel", "Psychic"],
	"bonsly": ["Rock"],
	"mimejr": ["Psychic", "Fairy"],
	"happiny": ["Normal"],
	"chatot": ["Normal", "Flying"],
	"spiritomb": ["Ghost", "Dark"],
	"gible": ["Dragon", "Ground"],
	"gabite": ["Dragon", "Ground"],
	"garchomp": ["Dragon", "Ground"],
	"garchompmega": ["Dragon", "Ground"],
	"munchlax": ["Normal"],
	"riolu": ["Fighting"],
	"lucario": ["Fighting", "Steel"],
	"lucariomega": ["Fighting", "Steel"],
	"hippopotas": ["Ground"],
	"hippowdon": ["Ground"],
	"skorupi": ["Poison", "Bug"],
	"drapion": ["Poison", "Dark"],
	"croagunk": ["Poison", "Fighting"],
	"toxicroak": ["Poison", "Fighting"],
	"carnivine": ["Grass"],
	"finneon": ["Water"],
	"lumineon": ["Water"],
	"mantyke": ["Water", "Flying"],
	"snover": ["Grass", "Ice"],
	"abomasnow": ["Grass", "Ice"],
	"abomasnowmega": ["Grass", "Ice"],
	"weavile": ["Dark", "Ice"],
	"magnezone": ["Electric", "Steel"],
	"lickilicky": ["Normal"],
	"rhyperior": ["Ground", "Rock"],
	"tangrowth": ["Grass"],
	"electivire": ["Electric"],
	"magmortar": ["Fire"],
	"togekiss": ["Fairy", "Flying"],
	"yanmega": ["Bug", "Flying"],
	"leafeon": ["Grass"],
	"glaceon": ["Ice"],
	"gliscor": ["Ground", "Flying"],
	"mamoswine": ["Ice", "Ground"],
	"porygonz": ["Normal"],
	"gallade": ["Psychic", "Fighting"],
	"gallademega": ["Psychic", "Fighting"],
	"probopass": ["Rock", "Steel"],
	"dusknoir": ["Ghost"],
	"froslass": ["Ice", "Ghost"],
	"rotom": ["Electric", "Ghost"],
	"rotomheat": ["Electric", "Fire"],
	"rotomwash": ["Electric", "Water"],
	"rotomfrost": ["Electric", "Ice"],
	"rotomfan": ["Electric", "Flying"],
	"rotommow": ["Electric", "Grass"],
	"uxie": ["Psychic"],
	"mesprit": ["Psychic"],
	"azelf": ["Psychic"],
	"dialga": ["Steel", "Dragon"],
	"palkia": ["Water", "Dragon"],
	"heatran": ["Fire", "Steel"],
	"regigigas": ["Normal"],
	"giratina": ["Ghost", "Dragon"],
	"giratinaorigin": ["Ghost", "Dragon"],
	"cresselia": ["Psychic"],
	"phione": ["Water"],
	"manaphy": ["Water"],
	"darkrai": ["Dark"],
	"shaymin": ["Grass"],
	"shayminsky": ["Grass", "Flying"],
	"arceus": ["Normal"],
	"arceusbug": ["Bug"],
	"arceusdark": ["Dark"],
	"arceusdragon": ["Dragon"],
	"arceuselectric": ["Electric"],
	"arceusfairy": ["Fairy"],
	"arceusfighting": ["Fighting"],
	"arceusfire": ["Fire"],
	"arceusflying": ["Flying"],
	"arceusghost": ["Ghost"],
	"arceusgrass": ["Grass"],
	"arceusground": ["Ground"],
	"arceusice": ["Ice"],
	"arceuspoison": ["Poison"],
	"arceuspsychic": ["Psychic"],
	"arceusrock": ["Rock"],
	"arceussteel": ["Steel"],
	"arceuswater": ["Water"],
	"victini": ["Psychic", "Fire"],
	"snivy": ["Grass"],
	"servine": ["Grass"],
	"serperior": ["Grass"],
	"tepig": ["Fire"],
	"pignite": ["Fire", "Fighting"],
	"emboar": ["Fire", "Fighting"],
	"oshawott": ["Water"],
	"dewott": ["Water"],
	"samurott": ["Water"],
	"patrat": ["Normal"],
	"watchog": ["Normal"],
	"lillipup": ["Normal"],
	"herdier": ["Normal"],
	"stoutland": ["Normal"],
	"purrloin": ["Dark"],
	"liepard": ["Dark"],
	"pansage": ["Grass"],
	"simisage": ["Grass"],
	"pansear": ["Fire"],
	"simisear": ["Fire"],
	"panpour": ["Water"],
	"simipour": ["Water"],
	"munna": ["Psychic"],
	"musharna": ["Psychic"],
	"pidove": ["Normal", "Flying"],
	"tranquill": ["Normal", "Flying"],
	"unfezant": ["Normal", "Flying"],
	"blitzle": ["Electric"],
	"zebstrika": ["Electric"],
	"roggenrola": ["Rock"],
	"boldore": ["Rock"],
	"gigalith": ["Rock"],
	"woobat": ["Psychic", "Flying"],
	"swoobat": ["Psychic", "Flying"],
	"drilbur": ["Ground"],
	"excadrill": ["Ground", "Steel"],
	"audino": ["Normal"],
	"audinomega": ["Normal", "Fairy"],
	"timburr": ["Fighting"],
	"gurdurr": ["Fighting"],
	"conkeldurr": ["Fighting"],
	"tympole": ["Water"],
	"palpitoad": ["Water", "Ground"],
	"seismitoad": ["Water", "Ground"],
	"throh": ["Fighting"],
	"sawk": ["Fighting"],
	"sewaddle": ["Bug", "Grass"],
	"swadloon": ["Bug", "Grass"],
	"leavanny": ["Bug", "Grass"],
	"venipede": ["Bug", "Poison"],
	"whirlipede": ["Bug", "Poison"],
	"scolipede": ["Bug", "Poison"],
	"cottonee": ["Grass", "Fairy"],
	"whimsicott": ["Grass", "Fairy"],
	"petilil": ["Grass"],
	"lilligant": ["Grass"],
	"basculin": ["Water"],
	"basculinbluestriped": ["Water"],
	"sandile": ["Ground", "Dark"],
	"krokorok": ["Ground", "Dark"],
	"krookodile": ["Ground", "Dark"],
	"darumaka": ["Fire"],
	"darmanitan": ["Fire"],
	"darmanitanzen": ["Fire", "Psychic"],
	"maractus": ["Grass"],
	"dwebble": ["Bug", "Rock"],
	"crustle": ["Bug", "Rock"],
	"scraggy": ["Dark", "Fighting"],
	"scrafty": ["Dark", "Fighting"],
	"sigilyph": ["Psychic", "Flying"],
	"yamask": ["Ghost"],
	"cofagrigus": ["Ghost"],
	"tirtouga": ["Water", "Rock"],
	"carracosta": ["Water", "Rock"],
	"archen": ["Rock", "Flying"],
	"archeops": ["Rock", "Flying"],
	"trubbish": ["Poison"],
	"garbodor": ["Poison"],
	"zorua": ["Dark"],
	"zoroark": ["Dark"],
	"minccino": ["Normal"],
	"cinccino": ["Normal"],
	"gothita": ["Psychic"],
	"gothorita": ["Psychic"],
	"gothitelle": ["Psychic"],
	"solosis": ["Psychic"],
	"duosion": ["Psychic"],
	"reuniclus": ["Psychic"],
	"ducklett": ["Water", "Flying"],
	"swanna": ["Water", "Flying"],
	"vanillite": ["Ice"],
	"vanillish": ["Ice"],
	"vanilluxe": ["Ice"],
	"deerling": ["Normal", "Grass"],
	"sawsbuck": ["Normal", "Grass"],
	"emolga": ["Electric", "Flying"],
	"karrablast": ["Bug"],
	"escavalier": ["Bug", "Steel"],
	"foongus": ["Grass", "Poison"],
	"amoonguss": ["Grass", "Poison"],
	"frillish": ["Water", "Ghost"],
	"jellicent": ["Water", "Ghost"],
	"alomomola": ["Water"],
	"joltik": ["Bug", "Electric"],
	"galvantula": ["Bug", "Electric"],
	"ferroseed": ["Grass", "Steel"],
	"ferrothorn": ["Grass", "Steel"],
	"klink": ["Steel"],
	"klang": ["Steel"],
	"klinklang": ["Steel"],
	"tynamo": ["Electric"],
	"eelektrik": ["Electric"],
	"eelektross": ["Electric"],
	"elgyem": ["Psychic"],
	"beheeyem": ["Psychic"],
	"litwick": ["Ghost", "Fire"],
	"lampent": ["Ghost", "Fire"],
	"chandelure": ["Ghost", "Fire"],
	"axew": ["Dragon"],
	"fraxure": ["Dragon"],
	"haxorus": ["Dragon"],
	"cubchoo": ["Ice"],
	"beartic": ["Ice"],
	"cryogonal": ["Ice"],
	"shelmet": ["Bug"],
	"accelgor": ["Bug"],
	"stunfisk": ["Ground", "Electric"],
	"mienfoo": ["Fighting"],
	"mienshao": ["Fighting"],
	"druddigon": ["Dragon"],
	"golett": ["Ground", "Ghost"],
	"golurk": ["Ground", "Ghost"],
	"pawniard": ["Dark", "Steel"],
	"bisharp": ["Dark", "Steel"],
	"bouffalant": ["Normal"],
	"rufflet": ["Normal", "Flying"],
	"braviary": ["Normal", "Flying"],
	"vullaby": ["Dark", "Flying"],
	"mandibuzz": ["Dark", "Flying"],
	"heatmor": ["Fire"],
	"durant": ["Bug", "Steel"],
	"deino": ["Dark", "Dragon"],
	"zweilous": ["Dark", "Dragon"],
	"hydreigon": ["Dark", "Dragon"],
	"larvesta": ["Bug", "Fire"],
	"volcarona": ["Bug", "Fire"],
	"cobalion": ["Steel", "Fighting"],
	"terrakion": ["Rock", "Fighting"],
	"virizion": ["Grass", "Fighting"],
	"tornadus": ["Flying"],
	"tornadustherian": ["Flying"],
	"thundurus": ["Electric", "Flying"],
	"thundurustherian": ["Electric", "Flying"],
	"reshiram": ["Dragon", "Fire"],
	"zekrom": ["Dragon", "Electric"],
	"landorus": ["Ground", "Flying"],
	"landorustherian": ["Ground", "Flying"],
	"kyurem": ["Dragon", "Ice"],
	"kyuremblack": ["Dragon", "Ice"],
	"kyuremwhite": ["Dragon", "Ice"],
	"keldeo": ["Water", "Fighting"],
	"keldeoresolute": ["Water", "Fighting"],
	"meloetta": ["Normal", "Psychic"],
	"meloettapirouette": ["Normal", "Fighting"],
	"genesect": ["Bug", "Steel"],
	"genesectdouse": ["Bug", "Steel"],
	"genesectshock": ["Bug", "Steel"],
	"genesectburn": ["Bug", "Steel"],
	"genesectchill": ["Bug", "Steel"],
	"chespin": ["Grass"],
	"quilladin": ["Grass"],
	"chesnaught": ["Grass", "Fighting"],
	"fennekin": ["Fire"],
	"braixen": ["Fire"],
	"delphox": ["Fire", "Psychic"],
	"froakie": ["Water"],
	"frogadier": ["Water"],
	"greninja": ["Water", "Dark"],
	"greninjaash": ["Water", "Dark"],
	"bunnelby": ["Normal"],
	"diggersby": ["Normal", "Ground"],
	"fletchling": ["Normal", "Flying"],
	"fletchinder": ["Fire", "Flying"],
	"talonflame": ["Fire", "Flying"],
	"scatterbug": ["Bug"],
	"spewpa": ["Bug"],
	"vivillon": ["Bug", "Flying"],
	"vivillonfancy": ["Bug", "Flying"],
	"vivillonpokeball": ["Bug", "Flying"],
	"litleo": ["Fire", "Normal"],
	"pyroar": ["Fire", "Normal"],
	"flabebe": ["Fairy"],
	"floette": ["Fairy"],
	"floetteeternal": ["Fairy"],
	"florges": ["Fairy"],
	"skiddo": ["Grass"],
	"gogoat": ["Grass"],
	"pancham": ["Fighting"],
	"pangoro": ["Fighting", "Dark"],
	"furfrou": ["Normal"],
	"espurr": ["Psychic"],
	"meowstic": ["Psychic"],
	"meowsticf": ["Psychic"],
	"honedge": ["Steel", "Ghost"],
	"doublade": ["Steel", "Ghost"],
	"aegislash": ["Steel", "Ghost"],
	"aegislashblade": ["Steel", "Ghost"],
	"spritzee": ["Fairy"],
	"aromatisse": ["Fairy"],
	"swirlix": ["Fairy"],
	"slurpuff": ["Fairy"],
	"inkay": ["Dark", "Psychic"],
	"malamar": ["Dark", "Psychic"],
	"binacle": ["Rock", "Water"],
	"barbaracle": ["Rock", "Water"],
	"skrelp": ["Poison", "Water"],
	"dragalge": ["Poison", "Dragon"],
	"clauncher": ["Water"],
	"clawitzer": ["Water"],
	"helioptile": ["Electric", "Normal"],
	"heliolisk": ["Electric", "Normal"],
	"tyrunt": ["Rock", "Dragon"],
	"tyrantrum": ["Rock", "Dragon"],
	"amaura": ["Rock", "Ice"],
	"aurorus": ["Rock", "Ice"],
	"sylveon": ["Fairy"],
	"hawlucha": ["Fighting", "Flying"],
	"dedenne": ["Electric", "Fairy"],
	"carbink": ["Rock", "Fairy"],
	"goomy": ["Dragon"],
	"sliggoo": ["Dragon"],
	"goodra": ["Dragon"],
	"klefki": ["Steel", "Fairy"],
	"phantump": ["Ghost", "Grass"],
	"trevenant": ["Ghost", "Grass"],
	"pumpkaboo": ["Ghost", "Grass"],
	"pumpkaboosmall": ["Ghost", "Grass"],
	"pumpkaboolarge": ["Ghost", "Grass"],
	"pumpkaboosuper": ["Ghost", "Grass"],
	"gourgeist": ["Ghost", "Grass"],
	"gourgeistsmall": ["Ghost", "Grass"],
	"gourgeistlarge": ["Ghost", "Grass"],
	"gourgeistsuper": ["Ghost", "Grass"],
	"bergmite": ["Ice"],
	"avalugg": ["Ice"],
	"noibat": ["Flying", "Dragon"],
	"noivern": ["Flying", "Dragon"],
	"xerneas": ["Fairy"],
	"yveltal": ["Dark", "Flying"],
	"zygarde": ["Dragon", "Ground"],
	"zygarde10": ["Dragon", "Ground"],
	"zygardecomplete": ["Dragon", "Ground"],
	"diancie": ["Rock", "Fairy"],
	"dianciemega": ["Rock", "Fairy"],
	"hoopa": ["Psychic", "Ghost"],
	"hoopaunbound": ["Psychic", "Dark"],
	"volcanion": ["Fire", "Water"],
	"rowlet": ["Grass", "Flying"],
	"dartrix": ["Grass", "Flying"],
	"decidueye": ["Grass", "Ghost"],
	"litten": ["Fire"],
	"torracat": ["Fire"],
	"incineroar": ["Fire", "Dark"],
	"popplio": ["Water"],
	"brionne": ["Water"],
	"primarina": ["Water", "Fairy"],
	"pikipek": ["Normal", "Flying"],
	"trumbeak": ["Normal", "Flying"],
	"toucannon": ["Normal", "Flying"],
	"yungoos": ["Normal"],
	"gumshoos": ["Normal"],
	"grubbin": ["Bug"],
	"charjabug": ["Bug", "Electric"],
	"vikavolt": ["Bug", "Electric"],
	"crabrawler": ["Fighting"],
	"crabominable": ["Fighting", "Ice"],
	"oricorio": ["Fire", "Flying"],
	"oricoriopompom": ["Electric", "Flying"],
	"oricoriopau": ["Psychic", "Flying"],
	"oricoriosensu": ["Ghost", "Flying"],
	"cutiefly": ["Bug", "Fairy"],
	"ribombee": ["Bug", "Fairy"],
	"rockruff": ["Rock"],
	"lycanroc": ["Rock"],
	"lycanrocmidnight": ["Rock"],
	"lycanrocdusk": ["Rock"],
	"wishiwashi": ["Water"],
	"wishiwashischool": ["Water"],
	"mareanie": ["Poison", "Water"],
	"toxapex": ["Poison", "Water"],
	"mudbray": ["Ground"],
	"mudsdale": ["Ground"],
	"dewpider": ["Water", "Bug"],
	"araquanid": ["Water", "Bug"],
	"fomantis": ["Grass"],
	"lurantis": ["Grass"],
	"morelull": ["Grass", "Fairy"],
	"shiinotic": ["Grass", "Fairy"],
	"salandit": ["Poison", "Fire"],
	"salazzle": ["Poison", "Fire"],
	"stufful": ["Normal", "Fighting"],
	"bewear": ["Normal", "Fighting"],
	"bounsweet": ["Grass"],
	"steenee": ["Grass"],
	"tsareena": ["Grass"],
	"comfey": ["Fairy"],
	"oranguru": ["Normal", "Psychic"],
	"passimian": ["Fighting"],
	"wimpod": ["Bug", "Water"],
	"golisopod": ["Bug", "Water"],
	"sandygast": ["Ghost", "Ground"],
	"palossand": ["Ghost", "Ground"],
	"pyukumuku": ["Water"],
	"typenull": ["Normal"],
	"silvally": ["Normal"],
	"silvallybug": ["Bug"],
	"silvallydark": ["Dark"],
	"silvallydragon": ["Dragon"],
	"silvallyelectric": ["Electric"],
	"silvallyfairy": ["Fairy"],
	"silvallyfighting": ["Fighting"],
	"silvallyfire": ["Fire"],
	"silvallyflying": ["Flying"],
	"silvallyghost": ["Ghost"],
	"silvallygrass": ["Grass"],
	"silvallyground": ["Ground"],
	"silvallyice": ["Ice"],
	"silvallypoison": ["Poison"],
	"silvallypsychic": ["Psychic"],
	"silvallyrock": ["Rock"],
	"silvallysteel": ["Steel"],
	"silvallywater": ["Water"],
	"minior": ["Rock", "Flying"],
	"miniormeteor": ["Rock", "Flying"],
	"komala": ["Normal"],
	"turtonator": ["Fire", "Dragon"],
	"togedemaru": ["Electric", "Steel"],
	"mimikyu": ["Ghost", "Fairy"],
	"mimikyubusted": ["Ghost", "Fairy"],
	"bruxish": ["Water", "Psychic"],
	"drampa": ["Normal", "Dragon"],
	"dhelmise": ["Ghost", "Grass"],
	"jangmoo": ["Dragon"],
	"hakamoo": ["Dragon", "Fighting"],
	"kommoo": ["Dragon", "Fighting"],
	"tapukoko": ["Electric", "Fairy"],
	"tapulele": ["Psychic", "Fairy"],
	"tapubulu": ["Grass", "Fairy"],
	"tapufini": ["Water", "Fairy"],
	"cosmog": ["Psychic"],
	"cosmoem": ["Psychic"],
	"solgaleo": ["Psychic", "Steel"],
	"lunala": ["Psychic", "Ghost"],
	"nihilego": ["Rock", "Poison"],
	"buzzwole": ["Bug", "Fighting"],
	"pheromosa": ["Bug", "Fighting"],
	"xurkitree": ["Electric"],
	"celesteela": ["Steel", "Flying"],
	"kartana": ["Grass", "Steel"],
	"guzzlord": ["Dark", "Dragon"],
	"necrozma": ["Psychic"],
	"necrozmaduskmane": ["Psychic", "Steel"],
	"necrozmadawnwings": ["Psychic", "Ghost"],
	"necrozmaultra": ["Psychic", "Dragon"],
	"magearna": ["Steel", "Fairy"],
	"magearnaoriginal": ["Steel", "Fairy"],
	"marshadow": ["Fighting", "Ghost"],
	"poipole": ["Poison"],
	"naganadel": ["Poison", "Dragon"],
	"stakataka": ["Rock", "Steel"],
	"blacephalon": ["Fire", "Ghost"],
	"zeraora": ["Electric"],
	"missingno": ["Bird", "Normal"],
	"tomohawk": ["Flying", "Fighting"],
	"necturna": ["Grass", "Ghost"],
	"mollux": ["Fire", "Poison"],
	"aurumoth": ["Bug", "Psychic"],
	"malaconda": ["Dark", "Grass"],
	"cawmodore": ["Steel", "Flying"],
	"volkraken": ["Water", "Fire"],
	"plasmanta": ["Electric", "Poison"],
	"naviathan": ["Water", "Steel"],
	"crucibelle": ["Rock", "Poison"],
	"crucibellemega": ["Rock", "Poison"],
	"kerfluffle": ["Fairy", "Fighting"],
	"syclant": ["Ice", "Bug"],
	"revenankh": ["Ghost", "Fighting"],
	"pyroak": ["Fire", "Grass"],
	"fidgit": ["Poison", "Ground"],
	"stratagem": ["Rock"],
	"arghonaut": ["Water", "Fighting"],
	"kitsunoh": ["Steel", "Ghost"],
	"cyclohm": ["Electric", "Dragon"],
	"colossoil": ["Dark", "Ground"],
	"krilowatt": ["Electric", "Water"],
	"voodoom": ["Fighting", "Dark"],
	"syclar": ["Ice", "Bug"],
	"embirch": ["Fire", "Grass"],
	"flarelm": ["Fire", "Grass"],
	"breezi": ["Poison", "Flying"],
	"scratchet": ["Normal", "Fighting"],
	"necturine": ["Grass", "Ghost"],
	"cupra": ["Bug", "Psychic"],
	"argalis": ["Bug", "Psychic"],
	"brattler": ["Dark", "Grass"],
	"cawdet": ["Steel", "Flying"],
	"volkritter": ["Water", "Fire"],
	"snugglow": ["Electric", "Poison"],
	"floatoy": ["Water"],
	"caimanoe": ["Water", "Steel"],
	"pluffle": ["Fairy"],
	"pokestarufo": ["Flying", "Electric"],
	"pokestarufo2": ["Psychic", "Electric"],
	"pokestarbrycenman": ["Dark", "Psychic"],
	"pokestarmt": ["Steel"],
	"pokestarmt2": ["Steel", "Electric"],
	"pokestartransport": ["Steel"],
	"pokestargiant": ["Normal"],
	"pokestarhumanoid": ["Normal"],
	"pokestarmonster": ["Dark"],
	"pokestarf00": ["Steel", "Normal"],
	"pokestarf002": ["Steel", "Normal"],
	"pokestarspirit": ["Dark", "Ghost"],
	"pokestarblackdoor": ["Grass"],
	"pokestarwhitedoor": ["Fire"],
	"pokestarblackbelt": ["Fighting"],
	"pokestarufopropu2": ["Psychic", "Electric"],
};